CustomerBundle\Entity\Customer:
    type: entity
    table: null
    repositoryClass: CustomerBundle\Repository\CustomerRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        email:
            type: string
            length: 255

    oneToOne:
        address:
            targetEntity: Address
            joinColumn:
                name: address_id
                referencedColumnName: id

    lifecycleCallbacks: {  }
